sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: icYAffnV9Q0hCEn0ui9QP540c/zGsGKvIawuzs6VH9mrz5VxIfXYIc4lZjpaR5lASeOhx9E066+COvCos3ydHvRf4HVNMY6jUAwdyKEwbZBPC6vwXdugeGQzVHvFDtY0u7xH3iFvQlN6zjW018HouVWeGHV/Jng08PfH3mzU5Lg=
  email:
    recipients:
      secure: h+xEQoXxkdEkIC3SaL1OTcTtFOIArpFHWkwhPqE7Z25Nugza2ilyb9ikzxLw1s6veaBeF2Ena7WK12Item0nFsSyy5uz0oAa7MFqgFfnI2r/ISWpbewwzzNmUF2FQpSWCq8rIyCuQPJKyHHjzGEZKfmZuzk6gLgS3fNYqb9XYAs=
